### ISSUE TITLE
Add a license file

### ISSUE THREAD

**Issue by frdmn** [Boosik/boosCooldowns#9]

**Comment by SevereOverfl0w** [comment]
License isn't really necessary. This code is private by default.

**Comment by frdmn** [comment]
What do you mean with "private"? Not allowed to use for anyone else?

**Comment by Boosik** [comment]
GitHub projects are Copyright © by default. You may however use my work or it's derivates for private/commercial use. You are however not allowed to distribute my work for free or for commision.
